### ISSUE TITLE
create a .gitignore file

### ISSUE THREAD

**Issue by michaelgold** [orders-squad/orders#1]
**As a** developer 
**I need** to keep unwanted files off of the repo 
**So that** the repo stays secure and clutter free

**Assumptions:** 
* add a .vagrant folder to the repo
* it should not get checked in to the repo

**Acceptance Criteria:**
```
Given a .vagrant folder 
When I check it in
Then it should not appear in the repo
```

**Comment by LihengGong** [comment]
My understanding is that
- `.gitignore` is used in code submission,  specifying intentionally untracked files
- for issue template, `github/ISSUE_TEMPLATE.md` should be used.
