### ISSUE TITLE
Create new Space prod

### ISSUE THREAD

**Issue by EagleTongX** [orders-squad/orders#138]
**As a** developer 
**I need** to create a new space called prod
**So that** I can deploy to production when all integration tests pass

**Assumptions:** 
* add new space on Cloud Foundry

**Acceptance Criteria:**
```
Given the new space prod
When all integration test pass
Then we add production deploy stage to pipeline to deploy to production 
```

**Comment by LihengGong** [comment]
Already created prod space in Bluemix, so this issue can be closed.
