### ISSUE TITLE
Deny a refund request

### ISSUE THREAD

**Issue by michaelgold** [orders-squad/orders#15]
**As a** website administrator  
**I need** to deny a refund request
**So that** I can deny a refund to a customer

**Assumptions:** 
* After a website administrator clicks the "deny refund" button the order's status will be set to "refund-not-approved."

**Acceptance Criteria:**
```
When I call 'POST /order/{id}/deny-refund'
It changes the status of the order to 'refund_denied'

**Comment by 75divisha** [comment]
I think the effort level here is a 5

**Comment by michaelgold** [comment]
I think the effort is a 5 as well
