### ISSUE TITLE
Cancelled Orders

### ISSUE THREAD

**Issue by 75divisha** [orders-squad/orders#17]
As a product owner
I need a list of all cancelled orders
So that my customers can see what all ordered they cancelled 

Assumptions:
The customer can see the list of all cancelled orders under the orders
For each order, display ordered date and reason of cancellation

Acceptance Criteria:
When customer go under the orders 
Then they can see their all cancelled orders

**Comment by EagleTongX** [comment]
How about adding this to the display orders? As a section in display all orders, including formal orders and canceled orders.

**Comment by 75divisha** [comment]
We can add this in List all orders or display orders. But I think we should add some filter tab there.. so that if users list is very large then he/she can see orders based on some categories.

**Comment by 75divisha** [comment]
I think the effort level here is a 2

**Comment by LihengGong** [comment]
query + display list. should be 5.

**Comment by EagleTongX** [comment]
I agree with the effort 5

**Comment by LihengGong** [comment]
We decided to go with canceled refunds so I think we can close this story
