### ISSUE TITLE
Completed Orders

### ISSUE THREAD

**Issue by 75divisha** [orders-squad/orders#19]
As a product owner
I need a list of all Completed orders
So that my customers can see all the completed orders

Assumptions:
A customer can see the list of all completed orders under the orders
For each order, display ordered date, delivery date, amount and orderID

Acceptance Criteria:
When customer go under the orders 
Then they can see their all completed orders

**Comment by 75divisha** [comment]
I think the effort level here is a 2

**Comment by LihengGong** [comment]
Query + display list. should be 5.

**Comment by EagleTongX** [comment]
I think effort here is 5

**Comment by LihengGong** [comment]
We decided to to go with canceled refunds so I think we can close this issue.
