### ISSUE TITLE
List all orders

### ISSUE THREAD

**Issue by michaelgold** [orders-squad/orders#3]
**As a** customer
**I need** a list of all my orders 
**So that** I can see what I ordered and select one order to view the detail

**Assumptions:** 
* The customer can see the list of orders under the orders 
* For each order, display its delivery status on the top
* For each order, show product information and order summary including shipping address, order number and placed date

**Acceptance Criteria:**
```
When customer go under the orders 
Then they can see their orders' information
```

**Comment by michaelgold** [comment]
@EagleTongX these user stories for product features should come from the perspective of the specific user of the feature. 

Here are my suggestions for rewording this story.

> **As a** customer
> **I need** a list of all of my orders
> **So that** I can select a specific order to view the details of that order

Also, a question for us to think about:
What importamt information about the order will we display in this list view, and what information will we only display to the user in #4?

**Comment by michaelgold** [comment]
I think the effort level here is a 5

**Comment by 75divisha** [comment]
I think the effort level here is 5

**Comment by LihengGong** [comment]
Agree with 5

**Comment by LihengGong** [comment]
The “list all orders” function are also implemented. After create several orders, we can just list all the created orders by visiting `localhost:5000/api/orders` and if everything works fine, the list of all orders are displayed

**Comment by michaelgold** [comment]
I'm writing the test cases for this now
