### ISSUE TITLE
Display an order

### ISSUE THREAD

**Issue by michaelgold** [orders-squad/orders#4]
**As a** product owner
**I need** a display order function
**So that** my customers can see what their order's detailed information

**Assumptions:** 
* The customer can see their order information after placing an order
*  Show product information and order summary including shipping address, order number, and the date when it was placed 

**Acceptance Criteria:**
```

When customer finish checking out
Then they can see their order's information
```

**Comment by michaelgold** [comment]
Why was this closed?

**Comment by EagleTongX** [comment]
I plan to open a new issue combine display and issue #17

**Comment by michaelgold** [comment]
This story refers to displaying a specific order. #17 refers to all orders.

I believe #17 is an enhancement to #3. 
If I am understanding the story correctly, it will provide functionality that is outside of the required scope for the project. Let's discuss further on our call today.

**Comment by michaelgold** [comment]
I think the effort level here is a 2

**Comment by EagleTongX** [comment]
What about putting this after the list of orders? When the customer views the list of orders, they can select one order to view the detail and then goes to the display an order feature.

**Comment by 75divisha** [comment]
I think the effort level here is a 2

**Comment by 75divisha** [comment]
But when customer view the order on separate window then that window will contain detail information of the product. So working on new window will require more work.

**Comment by LihengGong** [comment]
> But when customer view the order on separate window then that window will contain detail information of the product. So working on new window will require more work.

Here we only consider the effort of implementing REST api(we do not consider the frontend). So I agree with the effort of 2.

**Comment by EagleTongX** [comment]
I think effort for this one is 5
