### ISSUE TITLE
Refactor microservice to use Flask-RESTful 

### ISSUE THREAD

**Issue by EagleTongX** [orders-squad/orders#74]
**As a** developer  
**I need** to refactor our microservice to use Flask-RESTful
**So that** our microservice follow the RESTful 

**Assumptions:** 
* refactor all service code to use Flask-RESTful

**Acceptance Criteria:**
```
Given the microservice using Flask-RESTful 
When ...
Then ...
```

**Comment by LihengGong** [comment]
Working on it now.

**Comment by LihengGong** [comment]
Started coding

**Comment by LihengGong** [comment]
Service can run now. Adding test cases for the refactored code.

**Comment by LihengGong** [comment]
Working on the test code

**Comment by LihengGong** [comment]
Still working on test code
