### ISSUE TITLE
Add support for cloud database hosting

### ISSUE THREAD

**Issue by 75divisha** [orders-squad/orders#79]
As a user
I need persistent database storage
So that I can access past orders

Assumptions:

* We will use postgres
* We will host with elephantSQL

Acceptance Criteria:

**Comment by LihengGong** [comment]
Eagle is helping to push the latest code to bluemix

**Comment by LihengGong** [comment]
Will use postgres now.

**Comment by LihengGong** [comment]
Bluemix supports postgres, so we'll use postgres in bluemix now

**Comment by LihengGong** [comment]
Since PostgreSQL is available in bluemix now, sticking to PostgreSQL is a good idea.
