### ISSUE TITLE
Add honcho code to start server on bluemix

### ISSUE THREAD

**Issue by michaelgold** [orders-squad/orders#88]
**As a** developer
**I need** to ensure that my app starts after it deploys
**So that** I can continuously deploy my app

**Assumptions:** 
* we will use a honcho to start the app

**Acceptance Criteria:**
```
Given I execute the honcho start command
When I start my server
Then the application should load
```

**Comment by michaelgold** [comment]
should we be using gunicorn?

**Comment by LihengGong** [comment]
> should we be using gunicorn?

Maybe in next sprint?

**Comment by LihengGong** [comment]
My comment is that we enable Honcho in this sprint and integrate gunicorn in next sprint
