### ISSUE TITLE
Add Delete all orders method

### ISSUE THREAD

**Issue by 75divisha** [orders-squad/orders#97]
Need to add delete all orders in service.py for BDD testing

**Comment by LihengGong** [comment]
Will take care of this issue.

**Comment by LihengGong** [comment]
According to Divisha, this issue is blocking BDD now.

**Comment by LihengGong** [comment]
Working on this one now

**Comment by 75divisha** [comment]
behave will test all the scenario as mention in order.feature and before running all the scenario it will first delete all the old orders and load new ones. So to delete all old orders, we have to make a request delete all orders which will be like 'requests.delete(context.base_url + '/orders')' So we need another delete method which should remove all order from the db on request http://localhost:5000/orders
